### ISSUE TITLE
'DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded' with certain JWT's

### ISSUE THREAD

**Issue by leonroy** [salcode/jwtdecode#8]
Seeing the below error (I added console.log) with some JWT's:

```
DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at decodeJWT (file:///Users/leon/Development/scratch/jwt/index.html:112:11)
    at HTMLTextAreaElement.onchange (file:///Users/leon/Development/scratch/jwt/index.html:83:7)
```

**Comment by salcode** [comment]
That is interesting. I've been unable to recreate this.

Do you have an example JWT that causes this?

Since you probably don't want to share a currently active JWT, maybe you could share a JWT whose expiration date has passed.

Thanks for reporting this.

**Comment by leonroy** [comment]
sure, can you email me on leon.roy@gmail.com - would prefer not to publicly share the JWT even if expired.

**Comment by leonroy** [comment]
if you can email me at leon.roy@gmail.com I can share the token - thanks

**Comment by salcode** [comment]
Great - I've sent you an email @leonroy 👍

Thank you!

**Comment by leonroy** [comment]
Thanks for checking, yeah I tried it on a different Mac and it worked.

I have no idea what the issue could be, might be machine (or browser extension specific). Feel free to close.

**Comment by salcode** [comment]
Thanks @leonroy!

Since this issue seems to be limited to the one machine, I'm going to mark this closed for now.

If this comes up again in the future, this issue will serve as a good starting point.
